In [1]:
import numpy as np
import pandas as pd
import re

# Exercises

##### Write a function named is_vowel. It should accept a string as input and use a regular expression to determine if the passed string is a vowel. While not explicity mentioned in the lesson, you can treat the result of re.search as a boolean value that indicates whether or not the regular expression matches the given string.

In [4]:
def is_vowel(string):
    """Function takes in a string and returns a boolean value that 
    indicates whether or not the regular expression matches the given
    string"""
    
    regex = r'[aeiouAEIOU]'
    return bool(re.search(regex, string))

In [5]:
print('i is a vowel:', is_vowel('i'))
print('z is a vowel:', is_vowel('z'))
print('A is a vowel:', is_vowel('A'))
print('M is a vowel:', is_vowel('M'))

i is a vowel: True
z is a vowel: False
A is a vowel: True
M is a vowel: False

##### Write a function named is_validusername that accepts a string as input. A valid username starts with a lowercase letter, and only consists of lowercase letters, numbers, or the character. It should also be no longer than 32 characters. The function should return either True or False depending on whether the passed string is a valid username.

In [6]:
def is_valid_username(string):
    """^ asserts position at start of a line

    Match a single character present in the list below [a-z]
    a-z matches a single character in the range between a (index 97) and z (index 122) (case sensitive)

    Match a single character present in the list below [a-zA-Z0-9_]
    {,31} matches the previous token between 0 and 31 times, as many times as possible, giving back as needed (greedy)
    a-z matches a single character in the range between a (index 97) and z (index 122) (case sensitive)
    A-Z matches a single character in the range between A (index 65) and Z (index 90) (case sensitive)
    0-9 matches a single character in the range between 0 (index 48) and 9 (index 57) (case sensitive)
    _ matches the character _ with index 9510 (5F16 or 1378) literally (case sensitive)
    """
    
    
    regex = r'^[a-z][a-zA-Z0-9_]{,31}$'
    return bool(re.search(regex, string))

In [9]:
print('thisisalongusernamethatprobablyexceedsthirtytwochractersnotsureletstest:', 
      is_valid_username('thisisalongusernamethatprobablyexceedsthirtytwochractersnotsureletstest'))
print('dragonslayer123:', is_valid_username('dragonslayer123'))

thisisalongusernamethatprobablyexceedsthirtytwochractersnotsureletstest: False
dragonslayer123: True

#### Write a regular expression to capture phone numbers. It should match all of the following: (210) 867 5309 , +1 210.867.5309 , 867-5309 , 210-867-5309

In [12]:
"""
Named Capture Group country_code (?P<country_code>\+\d+)?
? matches the previous token between zero and one times, as many times as possible, giving back as needed (greedy)
\+ matches the character + with index 4310 (2B16 or 538) literally (case sensitive)

\d matches a digit (equivalent to [0-9])
+ matches the previous token between one and unlimited times, as many times as possible, giving back as needed (greedy)
↵ matches the character ↵ with index 1010 (A16 or 128) literally (case sensitive)

\D matches any character that's not a digit (equivalent to [^0-9])
* matches the previous token between zero and unlimited times, as many times as possible, giving back as needed (greedy)
↵ matches the character ↵ with index 1010 (A16 or 128) literally (case sensitive)

Named Capture Group area_code (?P<area_code>\d{3})?
? matches the previous token between zero and one times, as many times as possible, giving back as needed (greedy)

\d matches a digit (equivalent to [0-9])
{3} matches the previous token exactly 3 times
↵ matches the character ↵ with index 1010 (A16 or 128) literally (case sensitive)

\D matches any character that's not a digit (equivalent to [^0-9])
* matches the previous token between zero and unlimited times, as many times as possible, giving back as needed (greedy)
↵ matches the character ↵ with index 1010 (A16 or 128) literally (case sensitive)

Named Capture Group exchange_code (?P<exchange_code>\d{3})

\d matches a digit (equivalent to [0-9])
{3} matches the previous token exactly 3 times
↵ matches the character ↵ with index 1010 (A16 or 128) literally (case sensitive)

\D matches any character that's not a digit (equivalent to [^0-9])
* matches the previous token between zero and unlimited times, as many times as possible, giving back as needed (greedy)
↵ matches the character ↵ with index 1010 (A16 or 128) literally (case sensitive)

Named Capture Group last_four (?P<last_four>\d{4})

\d matches a digit (equivalent to [0-9])
{4} matches the previous token exactly 4 times


The VERBOSE flag allows you to write regular expressions t
hat look nicer and are more readable by allowing you to visually separate logical sections of the pattern and add comments.
"""

regex = r'''
(?P<country_code>\+\d+)?
\D*
(?P<area_code>\d{3})?
\D*
(?P<exchange_code>\d{3})
\D*
(?P<last_four>\d{4})$
'''

numbers = pd.Series([
    '(210) 867 5309',
    '+1 210.867.5309',
    '867-5309',
    '210-867-5309',
], name='original')

pd.concat([numbers, numbers.str.extract(regex, re.VERBOSE)], axis=1)

          original country_code area_code exchange_code last_four
0   (210) 867 5309          NaN       210           867      5309
1  +1 210.867.5309           +1       210           867      5309
2         867-5309          NaN       NaN           867      5309
3     210-867-5309          NaN       210           867      5309

#### Use regular expressions to convert the dates below to the standardized year-month-day format.
 
- 02/04/19
- 02/05/19
- 02/06/19
- 02/07/19
- 02/08/19
- 02/09/19
- 02/10/19

In [13]:
"""
"
(\d+)/(\d+)/(\d+)', r'20\3-\1-\2
"
gm

1st Capturing Group (\d+)

\d matches a digit (equivalent to [0-9])
+ matches the previous token between one and unlimited times, as many times as possible, giving back as needed (greedy)
/ matches the character / with index 4710 (2F16 or 578) literally (case sensitive)

2nd Capturing Group (\d+)

\d matches a digit (equivalent to [0-9])
+ matches the previous token between one and unlimited times, as many times as possible, giving back as needed (greedy)
/ matches the character / with index 4710 (2F16 or 578) literally (case sensitive)

3rd Capturing Group (\d+)

\d matches a digit (equivalent to [0-9])
+ matches the previous token between one and unlimited times, as many times as possible, giving back as needed (greedy)

', r'20 matches the characters ', r'20 literally (case sensitive)
\3 matches the same text as most recently matched by the 3rd capturing group
- matches the character - with index 4510 (2D16 or 558) literally (case sensitive)
\1 matches the same text as most recently matched by the 1st capturing group
- matches the character - with index 4510 (2D16 or 558) literally (case sensitive)
\2 matches the same text as most recently matched by the 2nd capturing group
"""

dates = pd.Series([
    '02/04/19',
    '02/05/19',
    '02/06/19',
    '02/07/19',
    '02/08/19',
    '02/09/19',
    '02/10/19',
])
dates.str.replace(r'(\d+)/(\d+)/(\d+)', r'20\3-\1-\2', regex=True)

0    2019-02-04
1    2019-02-05
2    2019-02-06
3    2019-02-07
4    2019-02-08
5    2019-02-09
6    2019-02-10
dtype: object

#### GET /api/v1/sales?page=86 [16/Apr/2019:193452+0000] HTTP/1.1 {200} 510348 "python-requests/2.21.0" 97.105.19.58 POST /users_accounts/file-upload [16/Apr/2019:193452+0000] HTTP/1.1 {201} 42 "User-Agent: Mozilla/5.0 (X11; Fedora; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" 97.105.19.58 GET /api/v1/items?page=3 [16/Apr/2019:193453+0000] HTTP/1.1 {429} 3561 "python-requests/2.21.0" 97.105.19.58

In [14]:
logfiles = """GET /api/v1/sales?page=86 [16/Apr/2019:193452+0000] HTTP/1.1 {200} 510348 "python-requests/2.21.0" 97.105.19.58
POST /users_accounts/file-upload [16/Apr/2019:193452+0000] HTTP/1.1 {201} 42 "User-Agent: Mozilla/5.0 (X11; Fedora; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36" 97.105.19.58
GET /api/v1/items?page=3 [16/Apr/2019:193453+0000] HTTP/1.1 {429} 3561 "python-requests/2.21.0" 97.105.19.58"""

In [15]:
#Create a df with the original logfiles
df = pd.DataFrame()
#Create an original columns
df['original'] = logfiles.strip().split('\n')
df

                                            original
0  GET /api/v1/sales?page=86 [16/Apr/2019:193452+...
1  POST /users_accounts/file-upload [16/Apr/2019:...
2  GET /api/v1/items?page=3 [16/Apr/2019:193453+0...

In [18]:
"""
asserts position at start of a line

Named Capture Group method (?P<method>GET|POST)

1st Alternative GET

GET matches the characters GET literally (case sensitive)

2nd Alternative POST

POST matches the characters POST literally (case sensitive)
↵ matches the character ↵ with index 1010 (A16 or 128) literally (case sensitive)

\s matches any whitespace character (equivalent to [\r\n\t\f\v  ])
+ matches the previous token between one and unlimited times, as many times as possible, giving back as needed (greedy)
↵ matches the character ↵ with index 1010 (A16 or 128) literally (case sensitive)

Named Capture Group path (?P<path>.*?)

. matches any character (except for line terminators)
*? matches the previous token between zero and unlimited times, as few times as possible, expanding as needed (lazy)
↵ matches the character ↵ with index 1010 (A16 or 128) literally (case sensitive)

\s matches any whitespace character (equivalent to [\r\n\t\f\v  ])
+ matches the previous token between one and unlimited times, as many times as possible, giving back as needed (greedy)
↵ matches the character ↵ with index 1010 (A16 or 128) literally (case sensitive)
\[ matches the character [ with index 9110 (5B16 or 1338) literally (case sensitive)

Named Capture Group timestamp (?P<timestamp>.*?)

. matches any character (except for line terminators)
*? matches the previous token between zero and unlimited times, as few times as possible, expanding as needed (lazy)
\] matches the character ] with index 9310 (5D16 or 1358) literally (case sensitive)
↵ matches the character ↵ with index 1010 (A16 or 128) literally (case sensitive)

\s matches any whitespace character (equivalent to [\r\n\t\f\v  ])
+ matches the previous token between one and unlimited times, as many times as possible, giving back as needed (greedy)
↵ matches the character ↵ with index 1010 (A16 or 128) literally (case sensitive)

Named Capture Group http_version (?P<http_version>.*?)

. matches any character (except for line terminators)
*? matches the previous token between zero and unlimited times, as few times as possible, expanding as needed (lazy)
↵ matches the character ↵ with index 1010 (A16 or 128) literally (case sensitive)

\s matches any whitespace character (equivalent to [\r\n\t\f\v  ])
+ matches the previous token between one and unlimited times, as many times as possible, giving back as needed (greedy)
↵ matches the character ↵ with index 1010 (A16 or 128) literally (case sensitive)
\{ matches the character { with index 12310 (7B16 or 1738) literally (case sensitive)

Named Capture Group status (?P<status>\d+)

\d matches a digit (equivalent to [0-9])
+ matches the previous token between one and unlimited times, as many times as possible, giving back as needed (greedy)
\} matches the character } with index 12510 (7D16 or 1758) literally (case sensitive)
↵ matches the character ↵ with index 1010 (A16 or 128) literally (case sensitive)

\s matches any whitespace character (equivalent to [\r\n\t\f\v  ])
+ matches the previous token between one and unlimited times, as many times as possible, giving back as needed (greedy)
↵ matches the character ↵ with index 1010 (A16 or 128) literally (case sensitive)

Named Capture Group bytes_sent (?P<bytes_sent>\d+)

\d matches a digit (equivalent to [0-9])
+ matches the previous token between one and unlimited times, as many times as possible, giving back as needed (greedy)
↵ matches the character ↵ with index 1010 (A16 or 128) literally (case sensitive)

\s matches any whitespace character (equivalent to [\r\n\t\f\v  ])
+ matches the previous token between one and unlimited times, as many times as possible, giving back as needed (greedy)
↵ matches the character ↵ with index 1010 (A16 or 128) literally (case sensitive)

Named Capture Group user_agent (?P<user_agent>.+)

. matches any character (except for line terminators)
+ matches the previous token between one and unlimited times, as many times as possible, giving back as needed (greedy)
↵ matches the character ↵ with index 1010 (A16 or 128) literally (case sensitive)
\s matches any whitespace character (equivalent to [\r\n\t\f\v  ])
↵ matches the character ↵ with index 1010 (A16 or 128) literally (case sensitive)

Named Capture Group ip (?P<ip>.+)

. matches any character (except for line terminators)
+ matches the previous token between one and unlimited times, as many times as possible, giving back as needed (greedy)¥
"""




# Write the regexp
regexp = r'''
^(?P<method>GET|POST)
\s+
(?P<path>.*?)
\s+
\[(?P<timestamp>.*?)\]
\s+
(?P<http_version>.*?)
\s+
\{(?P<status>\d+)\}
\s+
(?P<bytes_sent>\d+)
\s+
"(?P<user_agent>.+)"
\s
(?P<ip>.+)
'''

# concat the capture groups onto my df
df = pd.concat([df, df.original.str.extract(regexp, re.VERBOSE)], axis = 1)

In [19]:
df

,original,method,path,timestamp,http_version,status,bytes_sent,user_agent,ip,method,path,timestamp,http_version,status,bytes_sent,user_agent,ip
0,GET /api/v1/sales?page=86 [16/Apr/2019:193452+...,GET,/api/v1/sales?page=86,16/Apr/2019:193452+0000,HTTP/1.1,200,510348,python-requests/2.21.0,97.105.19.58,GET,/api/v1/sales?page=86,16/Apr/2019:193452+0000,HTTP/1.1,200,510348,python-requests/2.21.0,97.105.19.58
1,POST /users_accounts/file-upload [16/Apr/2019:...,POST,/users_accounts/file-upload,16/Apr/2019:193452+0000,HTTP/1.1,201,42,User-Agent: Mozilla/5.0 (X11; Fedora; Fedora; ...,97.105.19.58,POST,/users_accounts/file-upload,16/Apr/2019:193452+0000,HTTP/1.1,201,42,User-Agent: Mozilla/5.0 (X11; Fedora; Fedora; ...,97.105.19.58
2,GET /api/v1/items?page=3 [16/Apr/2019:193453+0...,GET,/api/v1/items?page=3,16/Apr/2019:193453+0000,HTTP/1.1,429,3561,python-requests/2.21.0,97.105.19.58,GET,/api/v1/items?page=3,16/Apr/2019:193453+0000,HTTP/1.1,429,3561,python-requests/2.21.0,97.105.19.58